version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn bramley.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000:8000
    env_file:
      - ./bramley/bramley/.env.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles

volumes:
  static_volume: